project:
  type: website
  output-dir: docs

website:
  title: "Notas em Ciência e Engenharia Computacional"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  repo-url: https://github.com/pedrohnv/pedrohnv.github.io
  repo-actions: [edit, source, issue]

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true