title = "Computação & Eletromagnetismo"
baseurl = "https://comp-eletromag.netlify.com/"
DefaultContentLanguage = "br"
theme = "beautifulhugo"
googleAnalytics = 'UA-153119838-1'
pygmentsUseClasses = true
pygmentsCodeFences = true

[Params]
  subtitle = "Usando o computador para solucionar problemas de eletromagnetismo"
  dateFormat = "2.1.2006"

[Author]
  name = "Pedro H. N. Vieira"
  website = "https://comp-eletromag.netlify.com/"
  email = "pedrohnv@hotmail.com"
  github = "pedrohnv"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Notebooks"
    url = "https://github.com/pedrohnv/pedrohnv.github.io/tree/master/notebooks"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[[menu.main]]
    name = "Sobre"
    url = "about"
    weight = 10
