baseurl = "https://comp-eletromag.netlify.com/"
DefaultContentLanguage = "pt"
title = "Computação & Eletromagnetismo"
theme = "beautifulhugo"

[Params]
  subtitle = "Usando o computador para solucionar problemas de eletromagnetismo"
  dateFormat = "January 2, 2006"

[Author]
  name = "Pedro H. N. Vieira"
  website = "https://comp-eletromag.netlify.com/"
  email = "pedrohnv@hotmail.com"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
